// Organized shortcuts by difficulty level
const shortcutsByDifficulty = {
    noob: [
        { action: "Rotate 3D view", key: "MMB + Drag" },
        { action: "Zoom", key: "Mousewheel" },
        { action: "Pan", key: "Shift + MMB + Drag" },
        { action: "Select", key: "LMB" },
        { action: "Animation Playback", key: "Space" },
        { action: "Delete", key: "X" },
        { action: "Undo", key: "Ctrl + Z" },
        { action: "Redo", key: "Shift + Ctrl + Z" },
        { action: "Save", key: "Ctrl + S" },
        { action: "New File", key: "Ctrl + N" },
        { action: "Front View", key: "Numpad 1" },
        { action: "Right View", key: "Numpad 3" },
        { action: "Top View", key: "Numpad 7" },
        { action: "Move (Grab)", key: "G" },
        { action: "Scale", key: "S" },
        { action: "Rotate", key: "R" },
        { action: "Select All", key: "A" },
        { action: "Deselect All", key: "Alt + A" },
        { action: "Edit/Object Mode", key: "Tab" },
        { action: "Add Menu", key: "Shift + A" },
        { action: "Camera View", key: "Numpad 0" },
        { action: "Hide", key: "H" },
        { action: "Unhide All", key: "Alt + H" },
        { action: "Render Image", key: "F12" }
    ],
    easy: [
        { action: "Views Pie Menu", key: "` + Drag" },
        { action: "Rename Object", key: "F2" },
        { action: "Search", key: "F3" },
        { action: "Duplicate", key: "Shift + D" },
        { action: "Move along global axis", key: "G + X/Y/Z" },
        { action: "Scale along global axis", key: "S + X/Y/Z" },
        { action: "Rotate along global axis", key: "R + X/Y/Z" },
        { action: "Tool Shelf Toggle", key: "T" },
        { action: "Sidebar Toggle", key: "N" },
        { action: "Border Select", key: "B" },
        { action: "Circle Select", key: "C" },
        { action: "Extrude", key: "E" },
        { action: "Fill Face", key: "F" },
        { action: "Join Objects", key: "Ctrl + J" },
        { action: "Toggle X-Ray View", key: "Alt + Z" },
        { action: "Toggle Wireframe View", key: "Shift + Z" },
        { action: "Vertex Selection", key: "1" },
        { action: "Edge Selection", key: "2" },
        { action: "Face Selection", key: "3" },
        { action: "Center Selected", key: "Numpad ," },
        { action: "Shading Pie Menu", key: "Z" },
        { action: "Set Parent", key: "Ctrl + P" },
        { action: "Clear Parent", key: "Alt + P" },
        { action: "Merge Selected", key: "M" },
        { action: "Invert Selection", key: "Ctrl + I" },
        { action: "Quick Favorites", key: "Q" },
        { action: "Render Animation", key: "Ctrl + F12" }
    ],
    intermediate: [
        { action: "Loopcut", key: "Ctrl + R" },
        { action: "Bevel", key: "Ctrl + B" },
        { action: "Knife Cut", key: "K" },
        { action: "Inset", key: "I" },
        { action: "Separate", key: "P" },
        { action: "Recalculate Normals", key: "Shift + N" },
        { action: "Unwrap", key: "U" },
        { action: "Repeat Last Action", key: "Shift + R" },
        { action: "Select Linked", key: "Ctrl + L" },
        { action: "Shrink/Fatten", key: "Alt + S" },
        { action: "Extrude Menu", key: "Alt + E" },
        { action: "Apply Transform", key: "Ctrl + A" },
        { action: "Reset Position", key: "Alt + G" },
        { action: "Reset Rotation", key: "Alt + R" },
        { action: "Reset Scale", key: "Alt + S" },
        { action: "Proportional Editing Toggle", key: "O" },
        { action: "Select Grouped", key: "Shift + G" },
        { action: "Select Linked under Cursor", key: "L" },
        { action: "Insert Keyframe", key: "I" },
        { action: "Mark Seam", key: "Ctrl + E" },
        { action: "Pivot Pie Menu", key: "." },
        { action: "Orientation Pie Menu", key: "," },
        { action: "Snapping Pie Menu", key: "Shift + S" },
        { action: "Select Edge/Face Loop", key: "Alt + LMB" },
        { action: "Toggle Maximize Area", key: "Ctrl + Space" },
        { action: "Duplicate Linked", key: "Alt + D" },
        { action: "Hide Unselected", key: "Shift + H" },
        { action: "Local View", key: "/" },
        { action: "Proportional Edit Falloff Pie Menu", key: "Shift + O" }
    ],
    pro: [
        { action: "To Sphere", key: "Shift + Alt + S" },
        { action: "Shear", key: "Shift + Ctrl + Alt + S" },
        { action: "Select Edge Ring", key: "Ctrl + Alt + LMB" },
        { action: "Slide Edge Selection", key: "G + G" },
        { action: "Transform with locked Axis", key: "G/R/S + MMB" },
        { action: "Fly Navigation", key: "Shift + `" },
        { action: "Add F-Curve Modifier", key: "Shift + Ctrl + M" },
        { action: "Set Keyframe Easing Type", key: "Ctrl + E" },
        { action: "Add Driver", key: "Ctrl + D" },
        { action: "Remove Driver", key: "Ctrl + Alt + D" },
        { action: "Assign to Vertex Group", key: "Ctrl + G" },
        { action: "Align TopView to active face", key: "Shift + Numpad 7" },
        { action: "Remesh", key: "Ctrl + R" },
        { action: "Group", key: "Ctrl + G" },
        { action: "Ungroup", key: "Ctrl + Alt + G" },
        { action: "Mute Links", key: "Ctrl + Alt + RMB + Drag" },
        { action: "Face Sets Pie Menu", key: "Alt + W" },
        { action: "Auto-Masking Pie Menu", key: "Shift + Alt + A" },
        { action: "Smooth Curve", key: "Alt + S" },
        { action: "Align Camera to View", key: "Ctrl + Alt + Numpad 0" },
        { action: "Set Active Object as Camera", key: "Ctrl + Numpad 0" },
        { action: "Toggle Full Screen Area", key: "Ctrl + Alt + Space" },
        { action: "Toggle Clipping Border", key: "Alt + B" },
        { action: "Toggle Quad View", key: "Ctrl + Alt + Q" },
        { action: "Move along local axis", key: "G + XX/YY/ZZ" },
        { action: "Free Rotate", key: "R + R" },
        { action: "Snapping Toggle", key: "Shift + Tab" },
        { action: "Set Render Region", key: "Ctrl + B" },
        { action: "Reset Render Region", key: "Ctrl + Alt + B" },
        { action: "Select Mirror", key: "Ctrl + Shift + M" }
    ]
};

// All shortcuts combined for generating random incorrect answers
let allShortcuts = [];
for (const level in shortcutsByDifficulty) {
    allShortcuts = allShortcuts.concat(shortcutsByDifficulty[level]);
}
